name: Generate GitBlog README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main
    paths:
      - main.go

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  sync:
    name: Generate Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.1'
          cache: true
          cache-dependency-path: go.sum
      - run: go run main.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Readme
    
